local ls = require "luasnip"
local s = ls.snippet
local sn = ls.snippet_node
local conds = require "luasnip.extras.expand_conditions"
-- local isn = ls.indent_snippet_node
local t = ls.text_node
local i = ls.insert_node
-- local f = ls.function_node
local c = ls.choice_node
local d = ls.dynamic_node
-- local r = ls.restore_node
-- local events = require("luasnip.util.events")
-- local ai = require("luasnip.nodes.absolute_indexer")
-- local fmt = require("luasnip.extras.fmt").fmt
-- local extras = require("luasnip.extras")
-- local m = require("luasnip.extras").m
-- local l = require("luasnip.extras").l
-- local postfix = require("luasnip.extras.postfix").postfix

local snips = {}

local on_top = function()
  local cursor = vim.api.nvim_win_get_cursor(0)
  if cursor[1] <= 3 then
    return true
  end
  return false
end

local pipe = function(fns)
  return function(...)
    for _, fn in ipairs(fns) do
      if not fn(...) then
        return false
      end
    end
    return true
  end
end

snips = {
  s(
    { trig = "temp", dscr = "frequently used templates" },
    c(1, {
      sn(nil, {
        t {
          "%%%%%%%%%%%%%",
          "%  Default  %",
          "%%%%%%%%%%%%%",
          "",
          "% \\documentclass{article}",
          "",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "%              https://github.com/anstadnik/preprint-template.tex              %",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "",
          "% Download preprint.sty from the above url, and put it in the same folder with",
          "% this document",
          "",
          "\\documentclass[twocolumn]{article} % Method A for two-column formatting",
          "\\usepackage{preprint}",
          "",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "%                                     Font                                     %",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "",
          "\\RequirePackage[T1]{fontenc}",
          "\\RequirePackage[utf8]{inputenc}",
          "\\usepackage[lf]{ebgaramond}",
          "\\usepackage[oldstyle,scale=0.7]{sourcecodepro}",
          "",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "%                                   Packages                                   %",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "",
          "% \\begin{enumerate}[label=(\\alph*)]",
          "\\usepackage{enumitem}",
          "",
          "%% Math packages",
          "\\usepackage{amsmath, amsthm, amssymb, amsfonts}",
          "\\DeclareMathOperator*{\\argmin}{arg\\,min} % Jan Hlavacek",
          "\\DeclareMathOperator*{\\argmax}{arg\\,max} % Jan Hlavacek",
          "",
          "%% Algorithm",
          "\\usepackage{algorithmicx, algpseudocode}",
          "",
          "%% Bibliography options",
          "\\usepackage[numbers,square]{natbib}",
          "\\bibliographystyle{unsrtnat}",
          "",
          "%% General packages",
          "% https://tex.stackexchange.com/a/677",
          "\\usepackage{xcolor}		% colors for hyperlinks",
          "\\usepackage[colorlinks = true,",
          "            linkcolor = purple,",
          "            urlcolor  = blue,",
          "            citecolor = cyan,",
          "            anchorcolor = black]{hyperref}	% Color links to references, figures, etc.",
          "\\usepackage{booktabs} 		% professional-quality tables",
          "\\usepackage{xfrac}		% compact symbols for 1/2 (\\sfrac{1}{2}), etc.",
          "\\usepackage{microtype}		% microtypography",
          "\\usepackage{lineno}		% Line numbers",
          "\\usepackage{float}			% Allows for figures within multicol",
          "",
          "\\usepackage{lipsum}		%  Filler text",
          "",
          "%% Special figure caption options",
          "\\usepackage{newfloat}",
          "\\DeclareFloatingEnvironment[name={Supplementary Figure}]{suppfigure}",
          "\\usepackage{sidecap}",
          "\\sidecaptionvpos{figure}{c}",
          "",
          "%% Code listings",
          "\\usepackage{listings}",
          "",
          "% Section title spacing  options",
          "\\usepackage{titlesec}",
          "\\titlespacing\\section{0pt}{12pt plus 3pt minus 3pt}{1pt plus 1pt minus 1pt}",
          "\\titlespacing\\subsection{0pt}{10pt plus 3pt minus 3pt}{1pt plus 1pt minus 1pt}",
          "\\titlespacing\\subsubsection{0pt}{8pt plus 3pt minus 3pt}{1pt plus 1pt minus 1pt}",
          "",
          "% Columns",
          "\\usepackage{paracol}",
          "\\setlength{\\columnseprule}{0.5pt}",
          "",
          "%% Graphics",
          "% \\usepackage{graphicx}",
          "% \\pdfminorversion=7",
          "% \\usepackage{pgfplots}",
          "% \\pgfplotsset{compat=newest}",
          "% \\usepackage{tikz}",
          "% \\usetikzlibrary{calc}",
          "",
          "\\title{",
        },
        -- i(1, (((vim.api.nvim_buf_get_name(0):gsub(".tex", "")):gsub("_", " ")):gsub(".*/", ""))),
        i(1),
        t {
          "}",
          "\\usepackage{xwatermark}",
          "% Bottom watermark",
          "\\newwatermark[firstpage,color=gray!90,angle=0,scale=0.28,",
          "		xpos=0in,ypos=-5in]{*correspondence: \\texttt{andrii.stadnik@ucu.edu.ua}}",
          "",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "%                              Header and footer                               %",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "",
          "% \\usepackage{fancyhdr}",
          "% \\pagestyle{fancy}",
          "% \\setlength{\\headheight}{15pt}% Fix a warning",
          "% \\lhead{{\\sf\\scriptsize APPS@UCU}}",
          "% \\rhead{{\\sf\\scriptsize Autumn~2021}}",
          "% \\chead{{\\sf\\scriptsize Linear Algebra: Homework~1 @ DS master programme",
          "% }}",
          "% \\lfoot{}",
          "% \\rfoot{}",
          "% \\cfoot{\\rm\\thepage}",
          "% \\pagestyle{myheadings}",
          "% %\\markright{}",
          "% \\markboth{}{}",
          "",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "%                                  Page setup                                  %",
          "%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
          "",
          "% https://texblog.net/latex-archive/uncategorized/matrix-align-left-right/",
          "\\makeatletter",
          "\\renewcommand*\\env@matrix[1][*\\c@MaxMatrixCols c]{%",
          "	\\hskip -\\arraycolsep",
          "	\\let\\@ifnextchar\\new@ifnextchar",
          "	\\array{#1}}",
          "\\makeatother",
          "",
          "% https://castel.dev/post/lecture-notes-2/#what-is-inkscape",
          "% \\newcommand{\\incfig}[1]{%",
          "% 	\\def\\svgwidth{\\columnwidth}",
          "% 	\\import{./figures/}{#1.pdf_tex}",
          "% }",
          "",
          "% \\pdfsuppresswarningpagegroup=1",
          "",
          "\\usepackage{authblk}",
          "\\renewcommand*{\\Authfont}{\\bfseries}",
          "\\author[1]{Andrii Stadnik}",
          "% \\author[2]{Bob Jones\\orcidB{}}",
          "",
          "\\affil[1]{Data Science, Ukrainian Catholic University}",
          "% \\affil[2]{Department of Biology, University Y}",
          "",
          "\\begin{document}",
          "",
          "\\twocolumn[ % Method A for two-column formatting",
          "	\\begin{@twocolumnfalse} % Method A for two-column formatting",
          "		\\maketitle",
          "",
          "		\\begin{abstract}",
          "			Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Ut purus elit, vestibulum ut, placerat ac, adipiscing vitae, felis. Curabitur dictum gravida mauris. Nam arcu libero, nonummy eget, consectetuer id, vulputate a, magna. Donec vehicula augue eu neque. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Mauris ut leo. Cras viverra metus rhoncus sem. Nulla et lectus vestibulum urna fringilla ultrices. Phasellus eu tellus sit amet tortor gravida placerat. Integer sapien est, iaculis in, pretium quis, viverra ac, nunc. Praesent eget sem vel leo ultrices bibendum. Aenean faucibus. Morbi dolor nulla, malesuada eu, pulvinar at, mollis ac, nulla. Curabitur auctor semper nulla. Donec varius orci eget risus. Duis nibh mi, congue eu, accumsan eleifend, sagittis quis, diam. Duis eget orci sit amet orci dignissim rutrum. Nam dui ligula, fringilla a, euismod sodales, sollicitudin vel, wisi. Morbi auctor lorem non justo.",
          "		\\end{abstract}",
          "	\\end{@twocolumnfalse} % Method A for two-column formatting",
          "] % Method A for two-column formatting",
          "",
          "\\section{",
        },
        i(2),
        t {
          "}",
          "",
        },
        i(0),
        t {
          "",
          "\\end{document}",
        },
      })

      -- sn(nil, {
      -- 	t {
      -- 		'\\documentclass{article}',
      -- 		'\\input{~/Tex/preamble_meta}',
      -- 		'',
      -- 		'\\usepackage[margin=1in]{geometry}',
      -- 		'\\linespread{1.3}',
      -- 		'\\pagestyle{headings}',
      -- 		'',
      -- 		'% \\input{~/Tex/bibtexref}',
      -- 		'\\input{~/Tex/preamble_ref}',
      -- 		'',
      -- 		'\\title{',
      -- 	},
      -- 	i(1),
      -- 	t {
      -- 		'}',
      -- 		'% \\author{Andrii Stadnik}',
      -- 		'',
      -- 		'\\begin{document}',
      -- 		'',
      -- 		'',
      -- 	},
      -- 	i(2),
      -- 	t {
      -- 		'',
      -- 		'',
      -- 		'\\end{document}',
      -- 	},
      -- }),
      -- sn(nil, {
      -- 	t {
      -- 		'\\documentclass[aspectratio=169]{beamer}',
      -- 		'\\usetheme[mode=light]{nord}',
      -- 		'\\input{~/Tex/preamble_meta_b}',
      -- 		'',
      -- 		'\\graphicspath{{./assets/}}',
      -- 		'',
      -- 		'\\title[short title]{LONG TITLE}',
      -- 		'\\subtitle{subtitle}',
      -- 		'\\date{\\today}',
      -- 		'\\author{Andrii Stadnik}',
      -- 		'\\institute[short institute]{LONG INSTITUTE}',
      -- 		'\\titlegraphic{nus-logo}',
      -- 		'',
      -- 		'\\hypersetup{',
      -- 		'  colorlinks=true,',
      -- 		'  linkcolor={nordNine},',
      -- 		'  citecolor={nordNine},',
      -- 		'  urlcolor={nordNine}',
      -- 		'}',
      -- 		'',
      -- 		'\\begin{document}',
      -- 		'\\titlepage',
      -- 		'',
      -- 		'\\section*{Introduction}',
      -- 		'',
      -- 		'\\begin{frame}',
      -- 		'\t\\frametitle{Introduction}',
      -- 		'',
      -- 		'',
      -- 	},
      -- 	i(1),
      -- 	t {
      -- 		'',
      -- 		'',
      -- 		'\\end{frame}',
      -- 		'',
      -- 		'%',
      -- 		'',
      -- 		'\\section{Main Results}',
      -- 		'',
      -- 		'%',
      -- 		'',
      -- 		'\\section{Question?}',
      -- 		'',
      -- 		'\\end{document}',
      -- 	},
      -- }),
      -- sn(nil, {
      -- 	t {
      -- 		'\\documentclass[11pt]{amsart}',
      -- 		'',
      -- 		'% Standard Packages',
      -- 		'\\usepackage{amsmath}',
      -- 		'\\usepackage{amssymb}',
      -- 		'\\usepackage{amsthm}',
      -- 		'\\usepackage{enumitem}',
      -- 		'\\usepackage[T1]{fontenc}',
      -- 		'\\usepackage{mathtools}',
      -- 		'\\usepackage{microtype}',
      -- 		'\\usepackage[dvipsnames]{xcolor}',
      -- 		'\\usepackage[all,cmtip]{xy}',
      -- 		'',
      -- 		'% BibTeX and Ref',
      -- 		'\\usepackage[pagebackref]{hyperref}',
      -- 		'\\usepackage[alphabetic]{amsrefs}',
      -- 		'\\usepackage[capitalise]{cleveref}',
      -- 		'',
      -- 		'\\hypersetup{',
      -- 		'\tcolorlinks=true,',
      -- 		'\tlinkcolor=MidnightBlue,',
      -- 		'\tcitecolor=MidnightBlue,',
      -- 		'\tfilecolor=magenta,',
      -- 		'\turlcolor=MidnightBlue',
      -- 		'}',
      -- 		'',
      -- 		'% Pagestyle',
      -- 		'\\usepackage[margin=1in]{geometry}',
      -- 		'\\linespread{1.3}',
      -- 		'',
      -- 		'% Environments.',
      -- 		'\\theoremstyle{plain}',
      -- 		'\\newtheorem{theorem}{Theorem}[section]',
      -- 		'\\newtheorem{axiom}[theorem]{Axiom}',
      -- 		'\\newtheorem{conjecture}[theorem]{Conjecture}',
      -- 		'\\newtheorem{corollary}[theorem]{Corollary}',
      -- 		'\\newtheorem{hypothesis}[theorem]{Hypothesis}',
      -- 		'\\newtheorem{lemma}[theorem]{Lemma}',
      -- 		'\\newtheorem{proposition}[theorem]{Proposition}',
      -- 		'',
      -- 		'\\theoremstyle{definition}',
      -- 		'\\newtheorem{definition}[theorem]{Definition}',
      -- 		'\\newtheorem{assumption}[theorem]{Assumption}',
      -- 		'\\newtheorem{example}[theorem]{Example}',
      -- 		'\\newtheorem{question}[theorem]{Question}',
      -- 		'\\newtheorem*{ack}{Acknowledgement}',
      -- 		'',
      -- 		'\\theoremstyle{remark}',
      -- 		'\\newtheorem{claim}[theorem]{Claim}',
      -- 		'\\newtheorem{notation}[theorem]{Notation}',
      -- 		'\\newtheorem{fact}[theorem]{Fact}',
      -- 		'\\newtheorem{remark}[theorem]{Remark}',
      -- 		'\\newtheorem{setup}[theorem]{}',
      -- 		'\\newtheorem*{remark*}{Remark}',
      -- 		'\\newtheorem*{notation*}{Notation and Terminology}',
      -- 		'',
      -- 		'\\numberwithin{equation}{section}',
      -- 		'',
      -- 		'% Commands',
      -- 		'% Algebra',
      -- 		'\\DeclareMathOperator{\\Ann}{Ann}',
      -- 		'\\DeclareMathOperator{\\Ass}{Ass}',
      -- 		'\\DeclareMathOperator{\\Aut}{Aut}',
      -- 		'\\DeclareMathOperator{\\Frac}{Frac}',
      -- 		'\\DeclareMathOperator{\\HN}{HN}',
      -- 		'\\DeclareMathOperator{\\Span}{Span}',
      -- 		'\\DeclareMathOperator{\\Sym}{Sym}',
      -- 		'\\DeclareMathOperator{\\Tr}{Tr} % trace',
      -- 		'\\DeclareMathOperator{\\coeff}{coeff}',
      -- 		'\\DeclareMathOperator{\\length}{length}',
      -- 		'\\DeclareMathOperator{\\mult}{mult}',
      -- 		'\\DeclareMathOperator{\\ord}{ord}',
      -- 		'\\DeclareMathOperator{\\rank}{rank}',
      -- 		'\\DeclareMathOperator{\\rk}{rk}',
      -- 		'\\DeclareMathOperator{\\sign}{sign}',
      -- 		'\\DeclareMathOperator{\\trdeg}{tr.deg}',
      -- 		'',
      -- 		'% Groups',
      -- 		'\\DeclareMathOperator{\\GL}{GL}',
      -- 		'\\DeclareMathOperator{\\Gal}{Gal}',
      -- 		'\\DeclareMathOperator{\\PGL}{PGL}',
      -- 		'\\DeclareMathOperator{\\PSL}{PSL}',
      -- 		'\\DeclareMathOperator{\\SL}{SL}',
      -- 		'',
      -- 		'% Homological Algebra',
      -- 		'\\DeclareMathOperator{\\coker}{coker}',
      -- 		'\\DeclareMathOperator{\\Ext}{Ext}',
      -- 		'\\DeclareMathOperator{\\Hm}{H} % homology/cohomology',
      -- 		'\\DeclareMathOperator{\\Hom}{Hom}',
      -- 		'\\DeclareMathOperator{\\SExt}{\\mathcal{E}\\!\\mathit{xt}}',
      -- 		'\\DeclareMathOperator{\\SHom}{\\mathcal{H}\\!\\mathit{om}}',
      -- 		'\\DeclareMathOperator{\\Tor}{Tor}',
      -- 		'\\DeclareMathOperator{\\id}{id}',
      -- 		'\\DeclareMathOperator{\\im}{Im} % image',
      -- 		'',
      -- 		'% Geometry',
      -- 		'\\DeclareMathOperator{\\Alb}{Alb}',
      -- 		'\\DeclareMathOperator{\\Amp}{Amp}',
      -- 		'\\DeclareMathOperator{\\Bir}{Bir}',
      -- 		'\\DeclareMathOperator{\\Bs}{Bs}',
      -- 		'\\DeclareMathOperator{\\CH}{CH}',
      -- 		'\\DeclareMathOperator{\\Chow}{Chow}',
      -- 		'\\DeclareMathOperator{\\Cl}{Cl}',
      -- 		'\\DeclareMathOperator{\\Diff}{Diff}',
      -- 		'\\DeclareMathOperator{\\Div}{Div}',
      -- 		'\\DeclareMathOperator{\\End}{End}',
      -- 		'\\DeclareMathOperator{\\Exc}{Exc}',
      -- 		'\\DeclareMathOperator{\\Fix}{Fix}',
      -- 		'\\DeclareMathOperator{\\Grass}{Grass}',
      -- 		'\\DeclareMathOperator{\\Nklt}{Nklt}',
      -- 		'\\DeclareMathOperator{\\Pic}{Pic}',
      -- 		'\\DeclareMathOperator{\\Proj}{Proj}',
      -- 		'\\DeclareMathOperator{\\Res}{Res}',
      -- 		'\\DeclareMathOperator{\\SBs}{SBs}',
      -- 		'\\DeclareMathOperator{\\SEnd}{SEnd}',
      -- 		'\\DeclareMathOperator{\\Sing}{Sing}',
      -- 		'\\DeclareMathOperator{\\Spec}{Spec} % Spectrum',
      -- 		'\\DeclareMathOperator{\\Supp}{Supp} % Support',
      -- 		'\\DeclareMathOperator{\\Val}{Val}',
      -- 		'\\DeclareMathOperator{\\Vol}{Vol}',
      -- 		'\\DeclareMathOperator{\\ch}{ch}',
      -- 		'\\DeclareMathOperator{\\codim}{codim}',
      -- 		'\\DeclareMathOperator{\\discrep}{discrep} % discrepancy',
      -- 		'\\DeclareMathOperator{\\lct}{lct}',
      -- 		'\\DeclareMathOperator{\\td}{td}',
      -- 		'\\DeclareMathOperator{\\var}{\\mathcal{Var}}',
      -- 		'',
      -- 		'% Cones',
      -- 		'\\DeclareMathOperator{\\Nef}{Nef}',
      -- 		'\\DeclareMathOperator{\\NE}{NE}',
      -- 		'\\DeclareMathOperator{\\cNE}{\\overline{NE}} % Mori cone',
      -- 		'\\DeclareMathOperator{\\NS}{NS}',
      -- 		'\\DeclareMathOperator{\\Mob}{Mob}',
      -- 		'\\DeclareMathOperator{\\Mov}{Mov}',
      -- 		'\\DeclareMathOperator{\\PE}{PE}',
      -- 		'',
      -- 		'',
      -- 		'% Miscellaneous',
      -- 		'\\newcommand{\\Romannum}[1]{\\uppercase\\expandafter{\\romannumeral #1}}',
      -- 		'\\newcommand{\\romannum}[1]{\\romannumeral #1\\relax}',
      -- 		'',
      -- 		'\\DeclarePairedDelimiter{\\rup}{\\lceil}{\\rceil}',
      -- 		'\\DeclarePairedDelimiter{\\rdown}{\\lfloor}{\\rfloor}',
      -- 		'\\DeclarePairedDelimiter{\\abs}{\\lvert}{\\rvert}',
      -- 		'\\DeclarePairedDelimiter{\\norm}{\\lVert}{\\rVert}',
      -- 		'\\DeclarePairedDelimiterX{\\pair}[2]{\\langle}{\\rangle}{#1,#2}',
      -- 		'',
      -- 		'% Author, Title, etc.',
      -- 		'\\title[short title]',
      -- 		'{long title}',
      -- 		'',
      -- 		'\\author{Andrii Stadnik}',
      -- 		'\\address{Ukrainian Catholic University}',
      -- 		'\\email{andrii.stadnik@ucu.edu.ua}',
      -- 		'',
      -- 		'\\subjclass[2020]{',
      -- 		'% 37P55, % Arithmetic dynamics on general algebraic varieties',
      -- 		'% 14G05, % Rational points',
      -- 		'% 14E30, % Minimal model program (Mori theory, extremal rays)',
      -- 		'% 08A35. % Automorphisms and endomorphisms of algebraic structures',
      -- 		'}',
      -- 		'\\keywords{keywords}',
      -- 		'',
      -- 		'\\begin{document}',
      -- 		'',
      -- 		'\\begin{abstract}',
      -- 		'abstract',
      -- 		'\\end{abstract}',
      -- 		'',
      -- 		'\\maketitle',
      -- 		'\\tableofcontents',
      -- 		'',
      -- 		'\\section{Introduction}\\label{sec:introduction}',
      -- 		'',
      -- 		'',
      -- 	},
      -- 	i(1),
      -- 	t {
      -- 		'',
      -- 		'',
      -- 		'% References',
      -- 		'',
      -- 		'\\bibliographystyle{ieeetr}',
      -- 		'\\bibliography{Jiabibtex.bib}',
      -- 		'',
      -- 		'\\end{document}',
      -- 	},
      -- }),
      -- sn(nil, {
      -- 	t {
      -- 		'% version 27 March 2022',
      -- 		'\\documentclass[11pt,a4paper]{amsart}',
      -- 		'\\input{~/Tex/preamble_meta}',
      -- 		'',
      -- 		'\\usepackage[margin=1in]{geometry}',
      -- 		'\\linespread{1.3}',
      -- 		'\\pagestyle{headings}',
      -- 		'',
      -- 		'\\input{~/Tex/bibtexref}',
      -- 		'',
      -- 		'\\begin{document}',
      -- 		'',
      -- 		'\\title{Answers to  queries of the referee}',
      -- 		'\\maketitle',
      -- 		'',
      -- 		'Many thanks to the referee for very careful reading, critical questions, and the valuable suggestions',
      -- 		'to improve the paper.',
      -- 		'The following are the main changes based on the suggestions.',
      -- 		'',
      -- 		'\\par \\vskip 1pc',
      -- 		'\\textbf{Changes according to the comments of the referee:}',
      -- 		'',
      -- 		'{\\color{blue}(1)}.',
      -- 		'',
      -- 	},
      -- 	i(1),
      -- 	t {
      -- 		'',
      -- 		'',
      -- 		'\\normalsize',
      -- 		'\\textbf{Revision}:',
      -- 		'',
      -- 		'\\par \\vskip 1pc',
      -- 		'\t{\\color{blue}(2)}.',
      -- 		'',
      -- 		'',
      -- 		'% References',
      -- 		'',
      -- 		'\\bibliographystyle{ieeetr}',
      -- 		'\\bibliography{Jiabibtex.bib}',
      -- 		'',
      -- 		'\\end{document}',
      -- 	},
      -- }),
    }),
    { condition = pipe { on_top, conds.line_begin }, show_condition = on_top }
  ),
}

return snips
